# Generated by Django 3.2.11 on 2023-07-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('empleado', 'Empleado'), ('facturas', 'Facturas')], default='admin', max_length=20),
        ),
    ]
