# Generated by Django 4.2.2 on 2023-07-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaAnticipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_inicial_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('otros_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_caja_anticipos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Caja de Anticipos',
                'verbose_name_plural': 'Cajas de Anticipos',
            },
        ),
        migrations.CreateModel(
            name='CajaSkyCreditoSky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reintegros_devoluciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consignaciones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prestamos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reintegros_entre_cajas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_encargado_prestamo', models.CharField(max_length=50)),
                ('cartera_pagare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anticipos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuentas_por_pagar', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Caja Sky - Crédito Sky',
                'verbose_name_plural': 'Cajas Sky - Crédito Sky',
            },
        ),
        migrations.CreateModel(
            name='CarteraPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=50)),
                ('deudas_empresa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abonos_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intereses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cartera Pagaré',
                'verbose_name_plural': 'Carteras Pagaré',
            },
        ),
        migrations.CreateModel(
            name='ComparativoIngresosCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compras', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Comparativo Ingresos vs Compras',
                'verbose_name_plural': 'Comparativos Ingresos vs Compras',
            },
        ),
        migrations.CreateModel(
            name='CostosProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Costos de Producción',
                'verbose_name_plural': 'Costos de Producción',
            },
        ),
        migrations.CreateModel(
            name='CuadroEstadistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('ventas_por_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ponderado_materia_prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_ganancias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costos_produccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_rentabilidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_porcentaje_rentabilidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gastos_construccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentabilidad_neta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_rentabilidad_neta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crecimiento_ventas_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_crecimiento_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cuadro Estadístico',
                'verbose_name_plural': 'Cuadros Estadísticos',
            },
        ),
        migrations.CreateModel(
            name='CuentasPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
            },
        ),
        migrations.CreateModel(
            name='CuentasProveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Cuenta Proveedor',
                'verbose_name_plural': 'Cuentas Proveedores',
            },
        ),
        migrations.CreateModel(
            name='EntradaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Entrada de Materia Prima',
                'verbose_name_plural': 'Entradas de Materias Primas',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
        migrations.CreateModel(
            name='GastoConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Gasto Construcción',
                'verbose_name_plural': 'Gastos Construcción',
            },
        ),
        migrations.CreateModel(
            name='GastosTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller', models.CharField(max_length=50)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_compras_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_compras_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acumulado_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Gastos del Taller',
                'verbose_name_plural': 'Gastos del Taller',
            },
        ),
        migrations.CreateModel(
            name='InformeComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('total_maquinaria_equipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_materia_prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_inventario_maquinaria_equipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_inventario_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Informe de Comportamiento',
                'verbose_name_plural': 'Informes de Comportamiento',
            },
        ),
        migrations.CreateModel(
            name='InventarioMaquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinaria', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventario Maquinaria',
                'verbose_name_plural': 'Inventarios Maquinaria',
            },
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventario Stock',
                'verbose_name_plural': 'Inventarios Stock',
            },
        ),
        migrations.CreateModel(
            name='OtrosInventarioStockEntra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Otros Inventario Stock - Entra',
                'verbose_name_plural': 'Otros Inventarios Stock - Entra',
            },
        ),
        migrations.CreateModel(
            name='PedidoMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pedido de Materia Prima',
                'verbose_name_plural': 'Pedidos de Materias Primas',
            },
        ),
        migrations.CreateModel(
            name='RegistroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_costos', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Registro de Compra',
                'verbose_name_plural': 'Registros de Compras',
            },
        ),
        migrations.CreateModel(
            name='RegistroMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('dimensiones', models.CharField(max_length=50)),
                ('kilogramos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Registro de Material',
                'verbose_name_plural': 'Registros de Materiales',
            },
        ),
        migrations.CreateModel(
            name='SalidaMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Salida de Materia Prima',
                'verbose_name_plural': 'Salidas de Materias Primas',
            },
        ),
        migrations.CreateModel(
            name='VentasDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquinaria', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('comprobante', models.CharField(max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acumulado_ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ventas del Día',
                'verbose_name_plural': 'Ventas del Día',
            },
        ),
    ]
