# Generated by Django 3.2.11 on 2023-07-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('cc_nit', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('detalles', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estado', models.CharField(max_length=10)),
                ('forma_de_pago', models.CharField(max_length=20)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Registro de Crédito',
                'verbose_name_plural': 'Registros de Créditos',
            },
        ),
        migrations.CreateModel(
            name='RegistroFactura',
            fields=[
                ('factura_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('cc_nit', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.CharField(max_length=10)),
                ('forma_de_pago', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Registro de Factura',
                'verbose_name_plural': 'Registros de Facturas',
            },
        ),
        migrations.CreateModel(
            name='AbonosCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('cc_nit', models.CharField(max_length=20)),
                ('forma_de_pago', models.CharField(max_length=20)),
                ('valor_abono', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='func.registrocredito')),
            ],
        ),
    ]
