# Generated by Django 3.2.11 on 2023-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0003_auto_20230719_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofactura',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
