# Generated by Django 3.2.11 on 2023-08-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0003_archivoexcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofactura',
            name='factura_id',
        ),
    ]
