# Generated by Django 3.2.11 on 2023-08-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0004_remove_registrofactura_factura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfactura',
            name='add_product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='registro_factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='func.registrofactura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemfactura',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='func.inventariomaquinaria', verbose_name='Producto'),
        ),
    ]
