# Generated by Django 3.2.11 on 2023-08-11 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0005_auto_20230810_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfactura',
            name='registro_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='func.registrofactura'),
        ),
    ]
