# Generated by Django 3.2.11 on 2023-08-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0006_alter_itemfactura_registro_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrofactura',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
