# Generated by Django 3.2.11 on 2023-09-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0007_auto_20230828_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventariostock',
            old_name='material',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='inventariostock',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='entrada_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='entrada_kls',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='ponderado_stock',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='salida_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='salida_kls',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='stock_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventariostock',
            name='stock_kls',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
