# Generated by Django 3.2.11 on 2023-09-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func', '0008_auto_20230907_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariostock',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='entrada_cm',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='entrada_kls',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='ponderado_stock',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='salida_cm',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='salida_kls',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_cm',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventariostock',
            name='stock_kls',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
